- name: Create dataest directories
  file:
    path: "{{ datasets_dir }}/lubm/{{ item.name }}"
    state: directory
    mode: 0755
    owner: dataset
    group: dataset
  loop: "{{ lubm_datasets }}"

- name: Generate lubm datasets
  become_user: dataset
  shell:
    cmd: java -jar {{ datasets_dir }}/lubm/generator/lubm-uba.jar --consolidate Maximal --format NTRIPLES --threads {{ ansible_processor_vcpus }} --index {{ item.index }} --seed {{ item.seed }} --univ {{ item.number }} --ontology "{{ item.ontology | default('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl', true) }}" --output {{ datasets_dir }}/lubm/{{ item.name }}/ --timing --log {{ datasets_dir }}/lubm/{{ item.name }}/log.txt
    creates: "{{ datasets_dir }}/lubm/{{ item.name }}/log.txt"
  loop: "{{ lubm_datasets }}"
