- name: Create dataest directories
  file:
    path: /opt/datasets/lubm/{{ item.name }}
    state: directory
  loop: "{{ lubm_datasets }}"

- name: Generate lubm datasets
  command:
    argv:
      - sh
      - -c
      - mkdir /opt/datasets/lubm/{{ item.name }}/shards && java -jar /opt/datasets/lubm/generator/lubm-uba.jar --format NTRIPLES --threads {{ ansible_processor_vcpus }} --index {{ item.index }} --seed {{ item.seed }} --univ {{ item.number }} --ontology "{{ item.ontology | default('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl', true) }}" --output /opt/datasets/lubm/{{ item.name }}/shards --timing --log /opt/datasets/lubm/{{ item.name }}/log.txt && cat /opt/datasets/lubm/{{ item.name }}/shards/*.nt > /opt/datasets/lubm/{{ item.name }}/{{ item.name }}.nt && rm -r /opt/datasets/lubm/{{ item.name }}/shards
    creates: /opt/datasets/lubm/{{ item.name }}/log.txt
  loop: "{{ lubm_datasets }}"
