- name: Create dataest directories
  file:
    path: "{{ target_dir }}/datasets/lubm/{{ item.name }}"
    state: directory
  loop: "{{ lubm_datasets }}"

- name: Generate lubm datasets
  become_user: dataset
  command:
    cmd: java -jar {{ target_dir }}/datasets/lubm/generator/lubm-uba.jar --consolidate Maximal --format NTRIPLES --threads {{ ansible_processor_vcpus }} --index {{ item.index }} --seed {{ item.seed }} --univ {{ item.number }} --ontology "{{ item.ontology | default('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl', true) }}" --output {{ target_dir }}/datasets/lubm/{{ item.name }}/ --timing --log {{ target_dir }}/datasets/lubm/{{ item.name }}/log.txt
    creates: "{{ target_dir }}/datasets/lubm/{{ item.name }}/log.txt"
  loop: "{{ lubm_datasets }}"
