- name: Create Triplebit directory
  file:
    path: "{{ target_dir }}/triplestores/triplebit"
    state: directory

- name: Download Triplebit binaries
  get_url:
    url: https://github.com/dice-group/TripleBit/releases/download/2020-03-03/{{ item.name }}
    dest: "{{ target_dir }}/triplestores/triplebit/{{ item.name }}"
    checksum: "{{ item.checksum }}"
  loop:
    - name: buildTripleBitFromN3
      checksum: sha1:938ff68743463be65cd655e7466da0f64d935cf5
    - name: triplebitQuery
      checksum: sha1:daaae67a1488754a522ea748859527ed612dd7ac
