- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: gstore
  register: tempdir

- name: Download gStore
  get_url:
    url: https://github.com/dice-group/gStore-1/archive/tentris_paper_benchmark_settings.zip
    dest: "{{ tempdir.path }}/tentris_paper_benchmark_settings.zip"

- name: Unzip gStore
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/tentris_paper_benchmark_settings.zip"
    dest: "{{ tempdir.path }}"

- name: Prepare gStore Build
  command:
    chdir: "{{ tempdir.path }}/gStore-1-tentris_paper_benchmark_settings"
    argv:
      - make
      - pre

- name: Build gStore
  command:
    chdir: "{{ tempdir.path }}/gStore-1-tentris_paper_benchmark_settings"
    argv:
      - make

- name: Ensure gStore Directory is present
  file:
    path: "{{ target_dir }}/triplestores/gstore"
    state: directory

- name: Copy gStore binaries
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/gStore-1-tentris_paper_benchmark_settings/bin"
    dest: "{{ target_dir }}/triplestores/gstore"

- name: Copy gStore data
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/gStore-1-tentris_paper_benchmark_settings/data"
    dest: "{{ target_dir }}/triplestores/gstore"

- name: Copy gStore server files
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/gStore-1-tentris_paper_benchmark_settings/Server"
    dest: "{{ target_dir }}/triplestores/gstore"

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
