- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: gstore
  register: tempdir

- name: Download gStore
  get_url:
    url: https://github.com/dice-group/gStore-1/archive/adopt_cache_and_timeout.zip
    dest: "{{ tempdir.path }}/adopt_cache_and_timeout.zip"

- name: Unzip gStore
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/adopt_cache_and_timeout.zip"
    dest: "{{ tempdir.path }}"

- name: Prepare gStore Build
  command:
    chdir: "{{ tempdir.path }}/gStore-1-adopt_cache_and_timeout"
    argv:
      - make
      - pre

- name: Build gStore
  command:
    chdir: "{{ tempdir.path }}/gStore-1-adopt_cache_and_timeout"
    argv:
      - make

- name: Ensure gStore Directory is present
  file:
    path: "{{ target_dir }}/triplestores/gstore"
    state: directory

- name: Copy gStore binaries
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/gStore-1-adopt_cache_and_timeout/bin"
    dest: "{{ target_dir }}/triplestores/gstore"

- name: Copy gStore data
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/gStore-1-adopt_cache_and_timeout/data"
    dest: "{{ target_dir }}/triplestores/gstore"

- name: Copy gStore server files
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/gStore-1-adopt_cache_and_timeout/Server"
    dest: "{{ target_dir }}/triplestores/gstore"

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
