- name: Create Iguana suite directory
  file:
    path: "{{ target_dir }}/iguana_suites/"
    state: directory

- name: Create HTTP suite directories
  file:
    path: "{{ target_dir }}/iguana_suites/http/{{ item[0].name }}/{{ item[1].name }}"
    state: directory
  loop: "{{ triplestores_http | product(datasets) | list }}"

- name: Create HTTP suite directories for tentris
  file:
    path: "{{ target_dir }}/iguana_suites/http/tentris-{{ item[0] }}/{{ item[1].name }}"
    state: directory
  loop: "{{ tentris_versions | product(datasets) | list }}"

#- name: Template copy virtuoso config
#  template:
#    src: virtuoso-run.ini
#    dest: "{{ target_dir }}/triplestores/virtuoso/virtuoso-run-{{ item.name }}.ini"
#  loop: "{{ datasets }}"



- name: Template copy start scripts
  template:
    src: "{{ item[0].name }}-start.sh"
    dest: "{{ target_dir }}/iguana_suites/http/{{ item[0].name }}/{{ item[1].name }}/start.sh"
    mode: 0755
  loop: "{{ triplestores_http | product(datasets) | list }}"

- name: Template copy stop scripts
  template:
    src: "{{ item.name }}-stop.sh"
    dest: "{{ target_dir }}/iguana_suites/http/{{ item.name }}/stop.sh"
    mode: 0755
  loop: "{{ triplestores_http }}"

- name: Template copy Iguana DBpedia suites
  template:
    src: http-dbpedia.suite
    dest: "{{ target_dir }}/iguana_suites/http/{{ item.name }}/dbpedia2015/1.yml"
  loop: "{{ triplestores_http }}"



- name: Template copy SWDF start scripts
  template:
    src: "start-swdf.sh"
    dest: "{{ target_dir }}/iguana_suites/http/{{ item.name }}/swdf/start-fresh.sh"
    mode: 0755
  loop: "{{ triplestores_http }}"

- name: Template copy SWDF stop scripts
  template:
    src: "stop-swdf.sh"
    dest: "{{ target_dir }}/iguana_suites/http/{{ item.name }}/swdf/stop-fresh.sh"
    mode: 0755
  loop: "{{ triplestores_http }}"

- name: Template copy Iguana SWDF suites
  template:
    src: http-swdf.suite
    dest: "{{ target_dir }}/iguana_suites/http/{{ item.name }}/swdf/1.yml"
  loop: "{{ triplestores_http }}"



- name: Template copy tentris start scripts
  template:
    src: tentris-start.sh
    dest: "{{ target_dir }}/iguana_suites/http/tentris-{{ item[0] }}/{{ item[1].name }}/start.sh"
    mode: 0755
  loop: "{{ tentris_versions | product(datasets) | list }}"

- name: Template copy tentris stop scripts
  template:
    src: tentris-stop.sh
    dest: "{{ target_dir }}/iguana_suites/http/tentris-{{ item }}/stop.sh"
    mode: 0755
  loop: "{{ tentris_versions }}"

- name: Template copy Tentris Iguana DBpedia suite
  template:
    src: tentris-http-dbpedia.suite
    dest: "{{ target_dir }}/iguana_suites/http/tentris-{{ item }}/dbpedia2015/1.yml"
  loop: "{{ tentris_versions }}"



- name: Template copy tentris SWDF start scripts
  template:
    src: tentris-start-swdf.sh
    dest: "{{ target_dir }}/iguana_suites/http/tentris-{{ item }}/swdf/start-fresh.sh"
    mode: 0755
  loop: "{{ tentris_versions }}"

- name: Template copy tentris SWDF stop scripts
  template:
    src: tentris-stop-swdf.sh
    dest: "{{ target_dir }}/iguana_suites/http/tentris-{{ item }}/swdf/stop-fresh.sh"
    mode: 0755
  loop: "{{ tentris_versions }}"

- name: Template copy Tentris Iguana SWDF suite
  template:
    src: tentris-http-swdf.suite
    dest: "{{ target_dir }}/iguana_suites/http/tentris-{{ item }}/swdf/1.yml"
  loop: "{{ tentris_versions }}"


- name: Template copy SWDF suite run script
  template:
    src: iguana-run-swdf.sh
    dest: "{{ target_dir }}"
    mode: 0775

- name: Template copy DBpedia2015 suite run script
  template:
    src: iguana-run-dbpedia2015.sh
    dest: "{{ target_dir }}"
    mode: 0775
