- name: Create Iguana suite directory
  file:
    path: /opt/iguana_suites/
    state: directory

- name: Create HTTP suite directories
  file:
    path: /opt/iguana_suites/http/{{ item[0].name }}/{{ item[1].name }}
    state: directory
  loop: "{{ triplestores_http | product(datasets) | list }}"

- name: Create HTTP suite directories for tentris
  file:
    path: /opt/iguana_suites/http/tentris-{{ item }}/{{ item[1].name }}
    state: directory
  loop: "{{ tentris_versions | product(datasets) | list }}"

- name: Template copy start scripts
  template:
    src: "{{ item[0] }}-start.sh"
    dest: /opt/iguana_suites/http/{{ item[0].name }}/{{ item[1].name }}/{{ item[2] }}-start.sh
    mode: 0755
    owner: root
    group: root
  loop: "{{ triplestores | product(datasets, iguana_http_connections) | list }}"

- name: Template copy stop scripts
  template:
    src: "{{ item[0] }}-stop.sh"
    dest: /opt/loaders/{{ item[0] }}-stop-{{ item[1].name }}-{{ item[2].number }}.sh
    mode: 0755
    owner: root
    group: root
  loop: "{{ triplestores | product(datasets, iguana_http_connections) | list }}"

- name: Template copy Iguana HTTP suites
  template:
    src: http.suite
    dest: /opt/iguana_suites/http/{{ item[0].name }}/{{ item[1].name }}/{{ item[2] }}.suite
  loop: "{{ triplestores_http | product(datasets, iguana_http_connections) | list }}"

- name: Template copy tentris start scripts
  template:
    src: tentris-start.sh
    dest: /opt/iguana_suites/http/tentris-{{ item[0] }}/{{ item[1].name }}/{{ item[2] }}-start.sh
    mode: 0755
    owner: root
    group: root
  loop: "{{ tentris_versions | product(datasets) | list }}"

- name: Template copy tentris stop scripts
  template:
    src: tentris-stop.sh
    dest: /opt/loaders/tentris-{{ item[0] }}-stop-{{ item[1].name }}.sh
    mode: 0755
    owner: root
    group: root
  loop: "{{ tentris_versions | product(datasets) | list }}"

- name: Template copy Tentris Iguana HTTP suites
  template:
    src: tentris-http.suite
    dest: /opt/iguana_suites/http/tentris-{{ item[0] }}/{{ item[1].name }}/{{ item[2] }}.suite
  loop: "{{ tentris_versions | product(datasets, iguana_http_connections) | list }}"

- name: Create CLI suite directories
  file:
    path: /opt/iguana_suites/cli/{{ item.name }}
    state: directory
  loop: "{{ triplestores_cli }}"

- name: Create CLI suite directories for tentris
  file:
    path: /opt/iguana_suites/cli/tentris-{{ item }}
    state: directory
  loop: "{{ tentris_versions }}"

- name: Template copy Iguana CLI suites
  template:
    src: cli.suite
    dest: /opt/iguana_suites/cli/{{ item[0].name }}/{{ item[1].name }}.suite
  loop: "{{ triplestores_cli | product(datasets) | list }}"

- name: Template copy Tentris Iguana CLI suites
  template:
    src: tentris-cli.suite
    dest: /opt/iguana_suites/cli/tentris-{{ item[0] }}/{{ item[1].name }}.suite
  loop: "{{ tentris_versions | product(datasets) | list }}"
  