- name: Create RDF-3X Directory
  file:
    path: "{{ target_dir }}/triplestores/rdf3x"
    state: directory

- name: Download RDF-3X binaries
  get_url:
    url: https://github.com/dice-group/rdf-3x/releases/download/0.3.8/{{ item.name }}
    dest: "{{ target_dir }}/triplestores/rdf3x/{{ item.name }}"
    checksum: "{{ item.checksum }}"
    mode: 0755
  loop:
    - name: rdf3xdump
      checksum: sha1:ce230bd32c7f988aca83bfcb194d15b0e103a905
    - name: rdf3xembedded
      checksum: sha1:19703c71319eecbb54733cab04a0718f8c7cc87b
    - name: rdf3xload
      checksum: sha1:007e459ce5a5ee11b96aef61b10cc0300957a1c0
    - name: rdf3xquery
      checksum: sha1:1e8d9f55e9639b556c303cdd0989e0b035ca9db9
    - name: rdf3xreorg
      checksum: sha1:d78d138c5622bebb02758d5ce8472b0e6c2459ad
    - name: rdf3xupdate
      checksum: sha1:2d23f37e88314f79063a554a2bfcb187572f45fd
