- name: Check for the DBpedia dataset
  stat:
    path: "{{ datasets_dir }}/dbpedia/dbpedia351.nt"
    get_checksum: no
  register: dataset351_nt

- name: Create dataset directory
  file:
    path: "{{ datasets_dir }}/dbpedia"
    state: directory
    mode: 0755
    owner: dataset
    group: dataset

- include: download.yaml
  when: not dataset351_nt.stat.exists

- name: Download DBpedia queries
  get_url:
    url: 5fdbed8b1388d35bc77bc6e8cf3e8abfecc39683
    checksum: sha1:e6166484b527b941e063eac5bae527db2372c257
    dest: "{{ datasets_dir }}/dbpedia/queries.txt"
    mode: 0644
    owner: dataset
    group: dataset
