- name: Check for the DBpedia351 dataset (Turtle File)
  stat:
    path: "{{ datasets_dir }}/dbpedia/DBpedia351.ttl"
    get_checksum: no
  register: dataset351_ttl

- name: Check for the DBpedia2015 dataset (Turtle File)
  stat:
    path: "{{ datasets_dir }}/dbpedia/dbpedia_2015-10_en_wo-comments_c.ttl"
    get_checksum: no
  register: dataset2015_ttl

- name: Check for the DBpedia dataset
  stat:
    path: "{{ datasets_dir }}/dbpedia/dbpedia351.nt"
    get_checksum: no
  register: dataset351_nt

- name: Check for the DBpedia2015 dataset
  stat:
    path: "{{ datasets_dir }}/dbpedia/dbpedia_2015-10_en_wo-comments_c.nt"
    get_checksum: no
  register: dataset2015_nt

- include: download.yaml
  when: (not dataset351_nt.stat.exists and not dataset351_ttl.stat.exists) or (not dataset2015_nt.stat.exists and not dataset2015_ttl.stat.exists)

- include: convert.yaml
  when: not dataset351_nt.stat.exists or not dataset2015_nt.stat.exists

- name: Download DBpedia queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/VLDB2020_Tentris/queries/dbpedia.txt
    checksum: sha1:e6166484b527b941e063eac5bae527db2372c257
    dest: "{{ datasets_dir }}/dbpedia/dbpedia.txt"
    mode: 0644
    owner: dataset
    group: dataset
