- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: dbpedia2015
  register: tempdir

- name: Download DBpedia2015 dataset
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/ISWC2020_Tentris/dbpedia_2015-10_en_wo-comments_c.nt.zst
    checksum: sha1:5acb9f9aebdaeac7e5f30803949e1c37091771df
    dest: "{{ tempdir.path }}/dbpedia_2015-10_en_wo-comments_c.nt.zst"

- name: Install zstd
  become: yes
  apt:
    package: zstd

- name: Decompress DBpedia2015 dataset
  command:
    argv:
      - zstd
      - -d
      - "{{ tempdir.path }}/dbpedia_2015-10_en_wo-comments_c.nt.zst"
      - -o
      - "{{ target_dir }}/datasets/dbpedia2015/dbpedia_2015-10_en_wo-comments_c.nt"

- name: Copy DBpedia2015 queries
  copy:
    src: "{{ dbpedia2015_queries_file }}"
    dest: "{{ tempdir.path }}/dbpedia-queries.zip"

- name: Unzip DBpedia2015 queries
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/dbpedia-queries.zip"
    dest: "{{ target_dir }}/datasets/dbpedia2015/queries.txt"

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
