- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: dbpedia2015
  register: tempdir

- name: Download DBpedia2015 dataset
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/ISWC2020_Tentris/dbpedia_2015-10_en_wo-comments_c.nt.zst
    checksum: sha1:5acb9f9aebdaeac7e5f30803949e1c37091771df
    dest: "{{ tempdir.path }}/dbpedia_2015-10_en_wo-comments_c.nt.zst"

- name: Install zstd
  become: yes
  apt:
    package: zstd

- name: Decompress DBpedia2015 dataset
  command:
    argv:
      - zstd
      - -d
      - "{{ tempdir.path }}/dbpedia_2015-10_en_wo-comments_c.nt.zst"
      - -o
      - "{{ target_dir }}/datasets/dbpedia2015/dbpedia_2015-10_en_wo-comments_c.nt"

- name: Download DBpedia changesets
  shell: "wget -nc -r --accept '*.removed.nt.gz' https://downloads.dbpedia.org/live/changesets/2015/11/"
  args:
    chdir: "{{ tempdir.path }}"

- name: Decompress DBpedia changesets
  shell: "gunzip -r downloads.dbpedia.org"
  args:
    chdir: "{{ tempdir.path }}"

- name: Move DBpedia changesets
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/downloads.dbpedia.org/live/changesets"
    dest: "{{ target_dir }}/datasets/dbpedia2015/changesets"

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
