- name: Check for the DBpedia2015 dataset
  stat:
    path: "{{ target_dir }}/datasets/dbpedia2015/dbpedia_2015-10_en_wo-comments_c.nt"
    get_checksum: no
  register: dataset2015_nt

- name: Create dataset directory
  file:
    path: "{{ target_dir }}/datasets/dbpedia2015"
    state: directory

- include: download.yaml
  when: not dataset2015_nt.stat.exists

- name: Download DBpedia queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/2020_Tentris/DBpedia_2015-10/DBedia-2015-10.txt
    checksum: sha1:084739dd5ddab6a12630595fdfb158ea561dd168
    dest: "{{ target_dir }}/datasets/dbpedia2015/queries.txt"
