- name: Create Blazegraph directory
  file:
    path: "{{ target_dir }}/triplestores/blazegraph"
    state: directory

- name: Check for Blazegraph
  stat:
    path: "{{ target_dir }}/triplestores/blazegraph/blazegraph.jar"
  register: blazegraph

- name: Download Blazegraph JAR
  get_url:
    url: https://github.com/blazegraph/database/releases/download/BLAZEGRAPH_2_1_6_RC/blazegraph.jar
    dest: "{{ target_dir }}/triplestores/blazegraph/blazegraph.jar"
  when: not blazegraph.stat.exists

- name: Template copy application properties
  template:
    src: application.properties
    dest: "{{ target_dir }}/triplestores/blazegraph/application.properties"
