- name: Create Blazegraph directory
  file:
    path: /opt/blazegraph
    state: directory

- name: Check for Blazegraph
  stat:
    path: /opt/blazegraph/blazegraph.jar
  register: blazegraph

- name: Download Blazegraph JAR
  get_url:
    url: https://github.com/blazegraph/database/releases/download/BLAZEGRAPH_2_1_6_RC/blazegraph.jar
    dest: /opt/blazegraph/blazegraph.jar
  when: blazegraph.stat.exists == false
