- name: Create Blazegraph user
  user:
    name: blazegraph
    state: present
    system: yes
    create_home: no

- name: Create Blazegraph directory
  file:
    path: /opt/blazegraph
    state: directory

- name: Check for Blazegraph
  stat:
    path: /opt/blazegraph/blazegraph.jar
  register: blazegraph

- name: Download Blazegraph JAR
  get_url:
    url: https://github.com/blazegraph/database/releases/download/BLAZEGRAPH_2_1_6_RC/blazegraph.jar
    dest: /opt/blazegraph/blazegraph.jar
  when: blazegraph.stat.exists == false

- name: Template copy application properties
  template:
    src: application.properties
    dest: /opt/blazegraph/application.properties

- name: Template copy Blazegraph service
  template:
    src: blazegraph@.service
    dest: /etc/systemd/system/blazegraph@.service
  notify: Reload systemd

- name: Create Blazegraph database directory
  file:
    path: "{{ database_base_dir }}/blazegraph"
    state: directory
    mode: 0750
    owner: blazegraph
    group: blazegraph
