- name: Install python
  become: yes
  apt:
    package:
      - python3
      - python3-pip

- name: install conan server
  pip:
    name: conan

- name: conan server confdir
  file:
    path: ~/.conan_server
    state: directory

- name: conan server datadir
  file:
    path: ~/.conan_server/data
    state: directory

- name: copy conan server conf
  copy:
    src: server.conf
    dest: ~/.conan_server/server.conf

- name: Reset connection so that conan is in path
  meta: reset_connection

- name: add local conan registry
  command: conan remote add -f local http://localhost:9300
