- name: Install python
  become: yes
  apt:
    package:
      - python3
      - python3-pip

- name: install conan server
  pip:
    name: conan
    extra_args: --user

- name: Create a temporary conan server config directory
  tempfile:
    state: directory
    suffix: conan_server
  register: conan_server_tempdir

- name: Create conan server datadir
  file:
    path: "{{ conan_server_tempdir.path }}/data"
    state: directory

- name: Copy conan server conf
  template:
    src: server.conf
    dest: "{{ conan_server_tempdir.path }}/server.conf"
