- name: Install make & cmake
  apt:
    package:
      - make
      - cmake

- name: Install C++ Compiler
  apt:
    package:
      - gcc
      - g++

- name: Install git
  apt:
    package: git

- name: Install boost
  apt:
    package: libboost-all-dev

- name: Install readline
  apt:
    package: libreadline-dev

- name: Install libcurl
  apt:
    package: libcurl4-openssl-dev
