- name: Check for Virtuoso
  stat:
    path: /opt/virtuoso/{{ virtuoso_version }}/
  register: virtuoso_dir

- include: install.yaml
  when: not virtuoso_dir.stat.exists

- name: Template copy rdfloader sql query
  template:
    src: rdfloader.sql
    dest: /opt/virtuoso/rdfloader.sql

- name: Template copy virtuoso service
  template:
    src: virtuoso@.service
    dest: /etc/systemd/system/virtuoso@.service
  notify: Reload systemd
