- name: Ensure GraphDB Directory is present
  file:
    path: "{{ target_dir }}/triplestores/graphdb"
    state: directory

- name: Copy and unzip GraphDB
  unarchive:
    src: "{{ graphdb_local_zip_path }}"
    dest: "{{ target_dir }}/triplestores/graphdb/"
