- name: Ensure GraphDB Directory is present
  file:
    path: /opt/graphdb
    state: directory

- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: graphdb
  register: tempdir

- name: Download GraphDB
  get_url:
    url: http://download.ontotext.com/owlim/{{ graphdb_download_uuid }}/graphdb-free-9.1.1-dist.zip
    dest: "{{ tempdir.path }}/graphdb-free-{{ graphdb_version }}-dist.zip"
    checksum: sha1:ae0fa05bd4b03610e834bf3eaa18a7d33686adea

- name: Unzip GraphDB
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/graphdb-free-{{ graphdb_version }}-dist.zip"
    dest: /opt/graphdb/

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
