- name: Create GraphDB user
  user:
    name: graphdb
    state: present
    system: yes
    create_home: no

- name: Check for GraphDB
  stat:
    path: /opt/graphdb/graphdb-free-{{ graphdb_version }}/
  register: graphdb_dir

- include: install.yaml
  when: graphdb_dir.stat.exists == false

- name: Template copy GraphDB service
  template:
    src: graphdb@.service
    dest: /etc/systemd/system/graphdb@.service
  notify: Reload systemd

- name: Create GraphDB database directory
  file:
    path: "{{ database_base_dir }}/graphdb"
    state: directory
    mode: 0750
    owner: graphdb
    group: graphdb
