iguana_time_limit: 3600000
iguana_repetitions: 2 # TODO CHANGE
iguana_query_timeout: 180000
triplestores_http:
  - name: fuseki
    endpoint: http://localhost:3030/%d/sparql
    updateEndpoint: http://localhost:3030/%d/update

#  - name: fuseki-ltj
#    endpoint: http://localhost:3030/%d/sparql
#    updateEndpoint: http://localhost:3030/%d/update

#  - name: gstore
#    endpoint: http://localhost:9000/?db_name=%d
#    updateEndpoint: http://localhost:9000/?db_name=%d

#  - name: virtuoso
#    endpoint: http://localhost:8890/sparql
#    updateEndpoint: http://localhost:8890/sparql

  - name: graphdb
    endpoint: http://localhost:7200/repositories/%d
    updateEndpoint: http://localhost:7200/repositories/%d/statements

  - name: blazegraph
    endpoint: http://localhost:9999/blazegraph/sparql
    updateEndpoint: http://localhost:9999/blazegraph/sparql
