- name: Check for the wikidata dataset
  stat:
    path: "{{ target_dir }}/datasets/wikidata-2020-11-11"
  register: wikidata_dataset_dir

- include: download.yaml
  when: not wikidata_dataset_dir.stat.exists

- name: Download wikidata queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/tentris_compression/feasible-exmp-wikidata500-bgp-v3.txt
    checksum: sha1:227cd15cd90ffaf8e4f9ca3ba974b2337ee557ca
    dest: "{{ target_dir }}/datasets/wikidata-2020-11-11/queries.txt"
