- name: Check for the wikidata dataset
  stat:
    path: "{{ target_dir }}/datasets/wikidata-2020-11-11"
  register: wikidata_dataset_dir

- include: download.yaml
  when: not wikidata_dataset_dir.stat.exists

- name: Download wikidata queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/tentris_compression/feasible-exmp-wikidata500-bgp-queries.nt
    checksum: sha1:e03bdbd5cb43b35956bdc254f7dcd495cba6bc59
    dest: "{{ target_dir }}/datasets/wikidata-2020-11-11/queries.txt"
