- name: Check for cgmemtime
  stat:
    path: /usr/local/bin/cgmemtime
  register: cgmemtime_bin

- name: Check for cgmemtime cgroup
  stat:
    path: /sys/fs/cgroup/memory/cgmemtime
  register: cgmemtime_cgroup

- include: install.yaml
  when: not cgmemtime_bin.stat.exists

- name: Setup cgroup
  command:
    argv:
      - /usr/local/bin/cgmemtime
      - --setup
      - -g
      - user # The user that will execute the loading benchmarks must be in this group
      - --perm
      - "770"
  when: not cgmemtime_cgroup.stat.exists
