- name: Create Iguana Directory
  file:
    path: /opt/iguana-{{ iguana_version }}
    state: directory

- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: iguana
  register: tempdir

- name: Download Iguana Source
  get_url:
    url: https://github.com/dice-group/IGUANA/archive/{{ iguana_version }}.zip
    dest: "{{ tempdir.path }}/src.zip"

- name: Unzip Iguana Source
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/src.zip"
    dest: "{{ tempdir.path }}"

- name: Build Iguana
  command:
    chdir: "{{ tempdir.path }}/IGUANA-{{ iguana_version }}"
    argv:
      - mvn
      - -Dmaven.test.skip=true
      - clean
      - package

- name: Copy the Iguana Corecontroller JAR
  copy:
    src: "{{ tempdir.path }}/IGUANA-{{ iguana_version }}/iguana.corecontroller/target/iguana.corecontroller-2.1.2.jar"
    remote_src: yes
    dest: /opt/iguana-{{ iguana_version }}/corecontroller.jar

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
