- name: Create Iguana Directory
  file:
    path: "{{ target_dir }}/iguana-{{ iguana_version }}"
    state: directory

- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: iguana
 # register: tempdir

- name: Download Iguana
  get_url:
    url: https://github.com/dice-group/IGUANA/releases/download/{{ iguana_version }}/iguana.corecontroller-2.1.3.jar
    dest: "{{ target_dir }}/iguana-{{ iguana_version }}/corecontroller.jar"