- name: Check for Iguana
  stat:
    path: "{{ target_dir }}/iguana-{{ iguana_version }}"
  register: iguana_dir

- include: install.yaml
  when: not iguana_dir.stat.exists

- name: Install RabbitMQ
  become: yes
  apt:
    name: rabbitmq-server

- name: Search for brew in home
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_home

- name: Search for brew in user home
  stat:
    path: "{{ ansible_user_dir }}/.linuxbrew/bin/brew"
  register: brew_user_home

- name: Install homebrew
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh); echo eval \$($HOMEBREW_PREFIX/.linuxbrew/bin/brew shellenv)"
  when: not brew_home.stat.exists and not brew_user_home.stat.exists

- name: Install pypy3
  homebrew:
    path: "{{ ansible_user_dir }}/.linuxbrew/bin/:/home/linuxbrew/.linuxbrew/bin"
    package: pypy3

- name: clone CLI Iguana Source
  git:
    repo: "https://github.com/dice-group/ClassicLikeIguana.git"
    dest: "{{ target_dir }}/ClassicLikeIguana"

- name: Find the pip executable
  find:
    paths:
      - "{{ ansible_user_dir }}/.linuxbrew/bin/"
      - /home/linuxbrew/.linuxbrew/bin
    pattern: pip_pypy3
    file_type: any
  register: find_pip

- name: Install CLI Iguana requirements
  pip:
    executable: "{{ find_pip.files[0].path }}"
    requirements: "{{ target_dir }}/ClassicLikeIguana/reqirements.txt"

- name: Template copy iguana run script
  template:
    src: iguana-run.sh
    dest: "{{ target_dir }}/iguana-run.sh"
    mode: 0755

    executable: "{{ find_pip.files[0].path }}"
  template:
    src: iguana_cli-run.sh
    dest: "{{ target_dir }}/iguana_cli-run.sh"
    mode: 0755
