- name: Check for Iguana
  stat:
    path: /opt/iguana-{{ iguana_version.version_number }}
  register: iguana_dir

- include: install.yaml
  when: iguana_dir.stat.exists == false

- name: Template copy Iguana Corecontroller Service
  template:
    src: iguana-corecontroller.service
    dest: /etc/systemd/system/iguana-corecontroller.service
  notify: Reload and restart Iguana Corecontroller

- name: Template copy Iguana Resultprocessor Service
  template:
    src: iguana-resultprocessor.service
    dest: /etc/systemd/system/iguana-resultprocessor.service
  notify: Reload and restart Iguana Resultprocessor

- name: Template copy send-config script
  template:
    src: iguana-send-config.sh
    dest: /usr/local/bin/iguana-send-config.sh
    mode: 0755
    owner: root
    group: root
