- name: Check for Iguana
  stat:
    path: "{{ target_dir }}/iguana-{{ iguana_version }}"
  register: iguana_dir

- include: install.yaml
  when: not iguana_dir.stat.exists

- name: Template copy iguana run script
  template:
    src: iguana-run.sh
    dest: "{{ target_dir }}/iguana-run.sh"
    mode: 0755

- name: Template copy CLI iguana run script
  template:
    src: iguana_cli-run.sh
    dest: "{{ target_dir }}/iguana_cli-run.sh"
    mode: 0755
