- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: tentris
  register: tempdir

- name: Download tentris
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/VLDB2020_Tentris/releases/tentris_{{ tentris_version }}.zip
    dest: "{{ tempdir.path }}/tentris_{{ tentris_version }}.zip"

- name: Unzip tentris
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/tentris_{{ tentris_version }}.zip"
    dest: "{{ tempdir.path }}"

- name: Create installation directory
  file:
    path: "{{ target_dir }}/triplestores/tentris/{{ tentris_version }}"
    state: directory

- name: Install tentris_terminal
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/tentris_terminal"
    dest: "{{ target_dir }}/triplestores/tentris/{{ tentris_version }}/tentris_terminal"

- name: Install tentris_server
  copy:
    remote_src: yes
    src: "{{ tempdir.path }}/tentris_server"
    dest: "{{ target_dir }}/triplestores/tentris/{{ tentris_version }}/tentris_server"

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
