- name: Install build dependencies
  apt:
    package:
      - libserd-dev
      - uuid-dev

- name: Check for tentris
  stat:
    path: /opt/tentris/tentris_server
  register: tentris

- include: install.yaml
  when: tentris.stat.exists == false

- name: Template copy tentris service
  template:
    src: tentris@.service
    dest: /etc/systemd/system/tentris@.service
  notify: Reload systemd
