- name: Create tentris user
  user:
    name: tentris
    state: present
    system: yes
    create_home: no

- name: Install build dependencies
  apt:
    package:
      - libserd-dev
      - uuid-dev

- name: Check for tentris
  stat:
    path: /opt/tentris/tentris_server
  register: tentris

- include: install.yaml
  when: tentris.stat.exists == false

- name: Template copy tentris service
  template:
    src: tentris@.service
    dest: /etc/systemd/system/tentris@.service
  notify: Reload systemd

- name: Create tentris log directory
  file:
    path: /var/log/tentris
    state: directory
    mode: 0750
    owner: tentris
    group: tentris
