#- name: Install wordlist
#  apt:
#    package: wbritish-insane # It's only 1.3 MB
#    state: present

- name: Create the WatDiv directory
  file:
    path: "{{ datasets_dir }}/watdiv"
    state: directory
    mode: 0755
    owner: dataset
    group: dataset

- name: Check for the WatDiv Generator
  stat:
    path: "{{ datasets_dir }}/watdiv/generator/bin/Release/watdiv"
  register: generator

- include: install-generator.yaml
  when: generator.stat.exists == false

- include: run-generator.yaml

- name: Download the query file
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/VLDB2020_Tentris/queries/watdiv.txt
    dest: "{{ datasets_dir }}/watdiv/queries.txt"
    mode: 0644
    owner: dataset
    group: dataset
