- name: Create the WatDiv directory
  file:
    path: "{{ target_dir }}/datasets/watdiv"
    state: directory

- name: Check for the WatDiv Generator
  stat:
    path: "{{ target_dir }}/datasets/watdiv/generator/bin/Release/watdiv"
  register: generator

- include: install-generator.yaml
  when: not generator.stat.exists

- include: run-generator.yaml

- name: Download the query file
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/VLDB2020_Tentris/queries/watdiv.txt
    dest: "{{ target_dir }}/datasets/watdiv/queries.txt"
