- name: Create Fuseki user
  user:
    name: fuseki
    state: present
    system: yes
    create_home: no

- name: Check for Fuseki
  stat:
    path: /opt/fuseki/apache-jena-fuseki-{{ fuseki_version }}/
  register: fuseki_dir

- include: install.yaml
  when: fuseki_dir.stat.exists == false

- name: Ensure Fuseki is executable
  file:
    path: /opt/fuseki/apache-jena-fuseki-{{ fuseki_version }}/fuseki-server
    mode: 0755

- name: Template copy Fuseki service
  template:
    src: fuseki@.service
    dest: /etc/systemd/system/fuseki@.service
  notify: Reload systemd

- name: Create Fuseki database directory
  file:
    path: "{{ database_base_dir }}/fuseki"
    state: directory
    mode: 0750
    owner: fuseki
    group: fuseki
