- name: Create the dataset directory
  file:
    path: "{{ datasets_dir }}/swdf"
    state: directory
    mode: 0755
    owner: dataset
    group: dataset

- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: swdf
  register: tempdir

- name: Download SWDF dataset
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/VLDB2020_Tentris/datasets/swdf.zip
    checksum: sha1:ec3cfe8e0315d077519001d610e46e99918745dc
    dest: "{{ tempdir.path }}/swdf.zip"

- name: Unzip SWDF dataset
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/swdf.zip"
    dest: "{{ datasets_dir }}/swdf/"
    mode: 0644
    owner: dataset
    group: dataset

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
