- name: Check for the SWDF dataset
  stat:
    path: "{{ target_dir }}/datasets/swdf"
  register: dataset_dir

- include: download.yaml
  when: not dataset_dir.stat.exists

- name: Download SWDF queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/2020_Tentris/SWDF/swdf.txt
    checksum: sha1:37114a91eb94dd8ad99078a05a6dfe3a8dd9b917
    dest: "{{ target_dir }}/datasets/swdf/queries.txt"
